#opt
train_epoch: 100           # number of epochs
warmup_epoch: 0    # number of warm-up epochs
wd: 0.00001               # weight decay
lr: 0.0001
min_lr: 0

#dset
dataset: skin
B: 1
n_class: 2                            # number of classes
data_dir: '/localdisk/TCGA/all_files_together/'       # directory of dataset
n_worker: 32                          # number of workers
pin_memory: False                     # use pin memory in dataloader
n_shot: -1

# pretrained
backbone: 'ViT-S/16'
pretrain: 'medical_ssl'
D_feat: 384
D_inner: 128

split_path: "/home/lauren.jimenez/splits_cvpr/"


